spring:
  datasource:
    url: jdbc:h2:mem:client-db
  application:
    name: CLIENT-SERVICE
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: true
server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
